<a href="https://colab.research.google.com/github/Gopizone/DS/blob/main/Association_Rules(transactions_retail1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files=files.upload()

Saving transactions_retail1.csv to transactions_retail1.csv

# Import libraries

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder
# conda install -c conda-forge mlxtend

In [3]:
tr = pd.read_csv("transactions_retail1.csv")
tr

          'HANGING'        'HEART'   'HOLDER'    'T-LIGHT'     'WHITE'       NA
0         'LANTERN'        'METAL'    'WHITE'          NaN         NaN      NaN
1            'COAT'        'CREAM'    'CUPID'     'HANGER'    'HEARTS'      NaN
2          'BOTTLE'         'FLAG'      'HOT'    'KNITTED'     'UNION'  'WATER'
3          'HEART.'       'HOTTIE'      'RED'      'WHITE'    'WOOLLY'      NaN
4               '7'     'BABUSHKA'    'BOXES'    'NESTING'       'SET'      NaN
...             ...            ...        ...          ...         ...      ...
557035         '20'      'NAPKINS'       'OF'       'PACK'  'SPACEBOY'      NaN
557036      'APRON'  'CHILDREN''S'    'DOLLY'       'GIRL'         NaN      NaN
557037  'CHILDRENS'      'CUTLERY'    'DOLLY'       'GIRL'         NaN      NaN
557038  'CHILDRENS'       'CIRCUS'  'CUTLERY'     'PARADE'         NaN      NaN
557039          '9'       'BAKING'    'PIECE'  'RETROSPOT'       'SET'      NaN

[557040 rows x 6 columns]

In [4]:
tr1=tr.dropna()
tr1

       'HANGING'     'HEART'     'HOLDER'  'T-LIGHT'    'WHITE'           NA
2       'BOTTLE'      'FLAG'        'HOT'  'KNITTED'    'UNION'      'WATER'
13           '6'  'ASSORTED'        'BOX'   'COLOUR'       'OF'  'TEASPOONS'
31         'AND'      'CARD'       'GAME'    'HEADS'    'TAILS'    'VINTAGE'
33       'BOXES'       'OF4'      'ROUND'      'SET'    'SNACK'   'WOODLAND'
39           '2'         'I'     'LONDON'     'LOVE'      'SET'        'TEA'
...          ...         ...          ...        ...        ...          ...
556989       '6'        'OF'  'PERFECTLY'   'PRETTY'  'RIBBONS'        'SET'
556996   'FLOCK'     'FRAME'      'HEART'     'LOVE'    'PHOTO'        'RED'
557011      '12'     'CHALK'      'RETRO'      'SET'   'STICKS'      'WHITE'
557016       '6'   'BOTTLES'      'CRATE'       'IN'     'MILK'     'SCHOOL'
557021       '3'      'BEAK'    'HANGING'       'OF'    'OLLIE'       'OWLS'

[83150 rows x 6 columns]

# Pre-Processing
As the data is not in transaction formation 
We are using transaction Encoder

In [5]:
df=pd.get_dummies(tr1)
df

        'HANGING'_'&'  'HANGING'_'''N'''  ...  NA_'this'  NA_'to'
2                   0                  0  ...          0        0
13                  0                  0  ...          0        0
31                  0                  0  ...          0        0
33                  0                  0  ...          0        0
39                  0                  0  ...          0        0
...               ...                ...  ...        ...      ...
556989              0                  0  ...          0        0
556996              0                  0  ...          0        0
557011              0                  0  ...          0        0
557016              0                  0  ...          0        0
557021              0                  0  ...          0        0

[83150 rows x 1298 columns]

In [6]:
df.describe()

       'HANGING'_'&'  'HANGING'_'''N'''  ...     NA_'this'       NA_'to'
count   83150.000000       83150.000000  ...  83150.000000  83150.000000
mean        0.014143           0.000024  ...      0.000012      0.000024
std         0.118082           0.004904  ...      0.003468      0.004904
min         0.000000           0.000000  ...      0.000000      0.000000
25%         0.000000           0.000000  ...      0.000000      0.000000
50%         0.000000           0.000000  ...      0.000000      0.000000
75%         0.000000           0.000000  ...      0.000000      0.000000
max         1.000000           1.000000  ...      1.000000      1.000000

[8 rows x 1298 columns]

# Apriori Algorithm

In [15]:
frequent_itemsets = apriori(df, min_support=0.05, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.071161                                   ('HANGING'_'12')
1   0.054985                                    ('HANGING'_'2')
2   0.143235                                    ('HANGING'_'3')
3   0.084558                                    ('HANGING'_'4')
4   0.080505                                    ('HANGING'_'6')
5   0.053253                                   ('HANGING'_'60')
6   0.122225                                   ('HEART'_'CAKE')
7   0.092688                                 ('HOLDER'_'CASES')
8   0.102465                                    ('HOLDER'_'OF')
9   0.221227                                   ('T-LIGHT'_'OF')
10  0.060601                                  ('T-LIGHT'_'SET')
11  0.114504                                     ('WHITE'_'OF')
12  0.085833                                   ('WHITE'_'PACK')
13  0.127468                                    ('WHITE'_'SET')
14  0.194756                                         (NA_'SET')
15  0.057438                          (NA_'SET', 'HANGING'_'3')
16  0.057667                          (NA_'SET', 'HANGING'_'4')
17  0.053229                   ('HANGING'_'60', 'HEART'_'CAKE')
18  0.053229                 ('HANGING'_'60', 'HOLDER'_'CASES')
19  0.078040                 ('HEART'_'CAKE', 'HOLDER'_'CASES')
20  0.061563                   ('HEART'_'CAKE', 'T-LIGHT'_'OF')
21  0.085051                   ('WHITE'_'PACK', 'T-LIGHT'_'OF')
22  0.077270                         (NA_'SET', 'T-LIGHT'_'OF')
23  0.073037                           (NA_'SET', 'WHITE'_'OF')
24  0.053229  ('HANGING'_'60', 'HEART'_'CAKE', 'HOLDER'_'CAS...

In [17]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules

                           antecedents  ...   conviction
0                      ('HANGING'_'4')  ...     2.532052
1                     ('HANGING'_'60')  ...  1943.394083
2                     ('HANGING'_'60')  ...  2008.788960
3                   ('HOLDER'_'CASES')  ...     2.223888
4                     ('HEART'_'CAKE')  ...     2.509802
5                   ('HOLDER'_'CASES')  ...     5.554198
6                     ('HEART'_'CAKE')  ...     1.569126
7                     ('WHITE'_'PACK')  ...    85.509308
8                       ('WHITE'_'OF')  ...     2.223528
9     ('HANGING'_'60', 'HEART'_'CAKE')  ...          inf
10  ('HANGING'_'60', 'HOLDER'_'CASES')  ...          inf
11  ('HEART'_'CAKE', 'HOLDER'_'CASES')  ...     2.977916
12                    ('HANGING'_'60')  ...  2041.220132
13                  ('HOLDER'_'CASES')  ...     2.223945

[14 rows x 9 columns]

In [18]:
len(rules)

14

In [19]:
rules1 = association_rules(frequent_itemsets, metric="lift", min_threshold=0.6)
rules1

                           antecedents  ...   conviction
0                           (NA_'SET')  ...     1.215138
1                      ('HANGING'_'3')  ...     1.344330
2                           (NA_'SET')  ...     1.300523
3                      ('HANGING'_'4')  ...     2.532052
4                     ('HANGING'_'60')  ...  1943.394083
5                     ('HEART'_'CAKE')  ...     1.677146
6                     ('HANGING'_'60')  ...  2008.788960
7                   ('HOLDER'_'CASES')  ...     2.223888
8                     ('HEART'_'CAKE')  ...     2.509802
9                   ('HOLDER'_'CASES')  ...     5.554198
10                    ('HEART'_'CAKE')  ...     1.569126
11                    ('T-LIGHT'_'OF')  ...     1.216230
12                    ('WHITE'_'PACK')  ...    85.509308
13                    ('T-LIGHT'_'OF')  ...     1.485128
14                          (NA_'SET')  ...     1.290967
15                    ('T-LIGHT'_'OF')  ...     1.237465
16                          (NA_'SET')  ...     1.416829
17                      ('WHITE'_'OF')  ...     2.223528
18    ('HANGING'_'60', 'HEART'_'CAKE')  ...          inf
19  ('HANGING'_'60', 'HOLDER'_'CASES')  ...          inf
20  ('HEART'_'CAKE', 'HOLDER'_'CASES')  ...     2.977916
21                    ('HANGING'_'60')  ...  2041.220132
22                    ('HEART'_'CAKE')  ...     1.677189
23                  ('HOLDER'_'CASES')  ...     2.223945

[24 rows x 9 columns]

#####  An leverage value of 0 indicates independence. Range will be [-1 1]
A high conviction value means that the consequent is highly depending on the antecedent and range [0 inf]

In [20]:
rules.sort_values('lift',ascending = False)

                           antecedents  ...   conviction
12                    ('HANGING'_'60')  ...  2041.220132
11  ('HEART'_'CAKE', 'HOLDER'_'CASES')  ...     2.977916
9     ('HANGING'_'60', 'HEART'_'CAKE')  ...          inf
13                  ('HOLDER'_'CASES')  ...     2.223945
2                     ('HANGING'_'60')  ...  2008.788960
3                   ('HOLDER'_'CASES')  ...     2.223888
10  ('HANGING'_'60', 'HOLDER'_'CASES')  ...          inf
1                     ('HANGING'_'60')  ...  1943.394083
4                     ('HEART'_'CAKE')  ...     2.509802
5                   ('HOLDER'_'CASES')  ...     5.554198
7                     ('WHITE'_'PACK')  ...    85.509308
0                      ('HANGING'_'4')  ...     2.532052
8                       ('WHITE'_'OF')  ...     2.223528
6                     ('HEART'_'CAKE')  ...     1.569126

[14 rows x 9 columns]

In [21]:
rules[rules.lift>1]

                           antecedents  ...   conviction
0                      ('HANGING'_'4')  ...     2.532052
1                     ('HANGING'_'60')  ...  1943.394083
2                     ('HANGING'_'60')  ...  2008.788960
3                   ('HOLDER'_'CASES')  ...     2.223888
4                     ('HEART'_'CAKE')  ...     2.509802
5                   ('HOLDER'_'CASES')  ...     5.554198
6                     ('HEART'_'CAKE')  ...     1.569126
7                     ('WHITE'_'PACK')  ...    85.509308
8                       ('WHITE'_'OF')  ...     2.223528
9     ('HANGING'_'60', 'HEART'_'CAKE')  ...          inf
10  ('HANGING'_'60', 'HOLDER'_'CASES')  ...          inf
11  ('HEART'_'CAKE', 'HOLDER'_'CASES')  ...     2.977916
12                    ('HANGING'_'60')  ...  2041.220132
13                  ('HOLDER'_'CASES')  ...     2.223945

[14 rows x 9 columns]