<a href="https://colab.research.google.com/github/Gopizone/DS/blob/main/SVM(forestfires).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files=files.upload()

Saving forestfires.csv to forestfires.csv

In [2]:
# SVM Classification
import pandas as pd
import numpy as np
#from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
#from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [3]:
fire= pd.read_csv("forestfires.csv")

In [4]:
fire

    month  day  FFMC    DMC  ...  monthnov  monthoct  monthsep  size_category
0     mar  fri  86.2   26.2  ...         0         0         0          small
1     oct  tue  90.6   35.4  ...         0         1         0          small
2     oct  sat  90.6   43.7  ...         0         1         0          small
3     mar  fri  91.7   33.3  ...         0         0         0          small
4     mar  sun  89.3   51.3  ...         0         0         0          small
..    ...  ...   ...    ...  ...       ...       ...       ...            ...
512   aug  sun  81.6   56.7  ...         0         0         0          large
513   aug  sun  81.6   56.7  ...         0         0         0          large
514   aug  sun  81.6   56.7  ...         0         0         0          large
515   aug  sat  94.4  146.0  ...         0         0         0          small
516   nov  tue  79.5    3.0  ...         1         0         0          small

[517 rows x 31 columns]

In [5]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
fire["month"] = label_encoder.fit_transform(fire["month"])
fire["day"] = label_encoder.fit_transform(fire["day"])
fire["size_category"] = label_encoder.fit_transform(fire["size_category"])

In [6]:
fire

     month  day  FFMC    DMC  ...  monthnov  monthoct  monthsep  size_category
0        7    0  86.2   26.2  ...         0         0         0              1
1       10    5  90.6   35.4  ...         0         1         0              1
2       10    2  90.6   43.7  ...         0         1         0              1
3        7    0  91.7   33.3  ...         0         0         0              1
4        7    3  89.3   51.3  ...         0         0         0              1
..     ...  ...   ...    ...  ...       ...       ...       ...            ...
512      1    3  81.6   56.7  ...         0         0         0              0
513      1    3  81.6   56.7  ...         0         0         0              0
514      1    3  81.6   56.7  ...         0         0         0              0
515      1    2  94.4  146.0  ...         0         0         0              1
516      9    5  79.5    3.0  ...         1         0         0              1

[517 rows x 31 columns]

In [9]:

X=fire.iloc[:,:11]
y=fire["size_category"]

In [10]:
X

     month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0        7    0  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1       10    5  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2       10    2  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3        7    0  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4        7    3  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..     ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512      1    3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513      1    3  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514      1    3  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515      1    2  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516      9    5  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 11 columns]

In [11]:
y

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

In [13]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 11), (361,), (156, 11), (156,))

### Grid Search CV

In [14]:
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [15]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'rbf'}, 0.7340840840840841)

In [16]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 73.07692307692307

array([[  1,  42],
       [  0, 113]])

In [17]:
clf1 = SVC(C= 15, gamma = 50)
clf1.fit(X , y)
y_pred = clf1.predict(X)
acc1 = accuracy_score(y, y_pred) * 100
print("Accuracy =", acc1)
confusion_matrix(y, y_pred)

Accuracy = 100.0

array([[139,   0],
       [  0, 378]])

In [18]:
#poly
clf2 = SVC()
param_grid = [{'kernel':['poly'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=15, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3, gamma=50,
                           kernel='rbf', max_iter=-1, probability=False,
                           random_state=None, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['poly']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [19]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'poly'}, 0.9695195195195195)

In [20]:
#Sigmoid
clf3 = SVC()
param_grid = [{'kernel':['sigmoid'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=15, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3, gamma=50,
                           kernel='rbf', max_iter=-1, probability=False,
                           random_state=None, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [21]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'sigmoid'}, 0.7340840840840841)